### ISSUE TITLE
Bad Gateway

### ISSUE THREAD

**Issue by Adramatech1** [ffxvs/sd-webui-complete-setup#1]
Hey there this looks great have a new project like this but after follow the intructions i only have the "Bat Wateway" error message when enter the .paperspacegradient.com.

While the WebUi load on the last step appears this message.

```
/notebooks/stable-diffusion-webui/modules/gradio_extensons.py:25: GradioDeprecationWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
  res = original_IOComponent_init(self, *args, **kwargs)
```

**Comment by ffxvs** [comment]
It seems I typed the wrong port for Paperspace, my bad.
Can you update the notebook again and try launching the web UI ?

**Comment by Adramatech1** [comment]
It worked! (At least untill papespace go down again) But the message still appears.

```

/notebooks/stable-diffusion-webui/modules/gradio_extensons.py:25: GradioDeprecationWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
  res = original_IOComponent_init(self, *args, **kwargs)
```
_btw there is a little typo in "other Lora" on the sd15_Resource_List_

**Comment by ffxvs** [comment]
> ```
> /notebooks/stable-diffusion-webui/modules/gradio_extensons.py:25: GradioDeprecationWarning: `height` is deprecated in `Interface()`, please use it within `launch()` instead.
>   res = original_IOComponent_init(self, *args, **kwargs)
> ```

That's because the Web UI still uses the old version of Gradio. Possibility to maintain compatibility with existing extensions. I guess it doesn't matter because the warning is harmless


> _btw there is a little typo in "other Lora" on the sd15_Resource_List_

Fix! thanks for your report.
If there are no more problems, we can close this issue.
