### ISSUE TITLE
New Forge with Flux update?

### ISSUE THREAD

**Issue by coldasicee** [ffxvs/sd-webui-complete-setup#10]
Like title said, can we get an update to run the new forge? I want to try Flux

**Comment by gilroff** [comment]
yes plss

**Comment by Tales404** [comment]
oh yes that would be nice! :)
Loved your paperspace Notebook!

**Comment by ffxvs** [comment]
I'm also keeping an eye on the Flux's development.
But I'm still in the process of reworking the entire code to make the installation/update process easier. 
So, it might take some time.

**Comment by ffxvs** [comment]
The new Forge for Runpod is almost complete. But it's still in the dev branch. 
If anyone wants to try it, you can edit the Container image in [this template](https://runpod.io/console/deploy?template=kwef1wl832&ref=synjcfeg) to `ffxvs/sd-webui-containers:forge-dev`.
For Flux, I haven't made a notebook for Flux yet, so you'll have to download the models and stuff manually.

For Paperspace, I still need to do some integration with Paperspace. Stay tuned!

**Comment by ffxvs** [comment]
For further discussion please go here => [Progress on The New Forge Notebooks](https://github.com/ffxvs/sd-webui-complete-setup/discussions/11)

**Comment by mertayd0** [comment]
After running the template, I updated the entire repository using the git pull command and was able to access the latest version for the Flux model. However, after downloading the clips and VAE files using the wget command, they appear in the UI, but the models I uploaded do not show up. When I try to move the models to another folder through Jupyter, Jupyter freezes. Is there a solution or another way to resolve this?
![Ekran görüntüsü 2024-09-11 142446](https://github.com/user-attachments/assets/615cde16-f5b1-4c32-9957-461afafcc458)
![Ekran görüntüsü 2024-09-11 142506](https://github.com/user-attachments/assets/8160bb9e-98c2-4489-9463-0ce64b184611)

**Comment by ffxvs** [comment]
> After running the template, I updated the entire repository using the git pull command and was able to access the latest version for the Flux model. However, after downloading the clips and VAE files using the wget command, they appear in the UI, but the models I uploaded do not show up. When I try to move the models to another folder through Jupyter, Jupyter freezes. Is there a solution or another way to resolve this?


@mertayd0 
Don't use git pull.
Read the announcement first.

> For further discussion please go here => [Progress on The New Forge Notebooks](https://github.com/ffxvs/sd-webui-complete-setup/discussions/11)

**Comment by mertayd0** [comment]
![image](https://github.com/user-attachments/assets/a9f0659c-6d0a-4d2b-b14b-001d9e47711b)
![image](https://github.com/user-attachments/assets/8e53c330-0249-42fe-afb1-491471c55620)
![image](https://github.com/user-attachments/assets/6ffc7347-5981-4414-a32e-89a57c92e284)

I can't generate images, it stucks and I also tried gguf q8 model and it deosn't appears in the model list.
(I tried with ae, clip and txx nothing changed.)
