### ISSUE TITLE
[Forge] Can't generate images after restarting the Web UI

### ISSUE THREAD

**Issue by ffxvs** [ffxvs/sd-webui-complete-setup#13]
![image](https://github.com/user-attachments/assets/a9f0659c-6d0a-4d2b-b14b-001d9e47711b)
![image](https://github.com/user-attachments/assets/8e53c330-0249-42fe-afb1-491471c55620)
![image](https://github.com/user-attachments/assets/6ffc7347-5981-4414-a32e-89a57c92e284)

I can't generate images, it stucks and I also tried gguf q8 model and it deosn't appears in the model list.
(I tried with ae, clip and txx nothing changed.)

_Originally posted by @mertayd0 in https://github.com/ffxvs/sd-webui-complete-setup/issues/10#issuecomment-2346120525_

**Comment by ffxvs** [comment]
I move the issue here @mertayd0
From what i see you restart the UI, right? Restarting the UI will cause unknown issues. 
If you want to restart the Web UI after changing settings or something, you just need to restart the `Launch Web UI` cell in Jupyterlab then reload the Web UI.

Also, I've added Q8_0 to the list.

**Comment by mertayd0** [comment]
Thanks!
