### ISSUE TITLE
setting up webui?

### ISSUE THREAD

**Issue by leviackermann59** [ffxvs/sd-webui-complete-setup#16]
sorry for this noob question, i keep getting this error when i use the new notebook for forge
'python: can't open file '/notebooks/stable-diffusion-webui-forge/webui.py': [Errno 2] No such file or directory'
there is no 'setup webui' cell for the new notebook tho

**Comment by ffxvs** [comment]
What's the output when you running the `1.1. Initialization` cell ?

And please try runnning this code on a new cell then copy the output :
```python
import os
print(os.environ.get('BRANCH_ID'))
print(os.environ.get('WEBUI_ID'))
print(os.environ.get('WEBUI_DIR'))
print(os.environ.get('PLATFORM_ID'))
print(os.environ.get('CONTAINER_VERSION'))
```
