### ISSUE TITLE
Webui.py not found error 

### ISSUE THREAD

**Issue by Mazhd** [ffxvs/sd-webui-complete-setup#19]
Hey sorry if this was asked before. I made a new project using the new container "ffxvs/sd-webui-containers:auto1111-2024.09.21" 

When I try to run the Webui I get this error: "python: can't open file '/notebooks/stable-diffusion-webui/webui.py': [Errno 2] No such file or directory" 

The 

> 1.1. Initialization

 output:
"⏳ Updating dependencies...
⏳ Creating shared storage directory...
⏳ Installing/Updating Stable Diffusion Web UI...
Download completed
Download completed"

However there is no webui.py inside stable-diffusion-webui.

I ran this block of code:
```python
import os
print(os.environ.get('BRANCH_ID'))
print(os.environ.get('WEBUI_ID'))
print(os.environ.get('WEBUI_DIR'))
print(os.environ.get('PLATFORM_ID'))
print(os.environ.get('CONTAINER_VERSION'))
``` 

This is the output:
main
AUTO1111
/stable-diffusion-webui
PAPERSPACE
2024.09.21

Thanks for the help :)

**Comment by ffxvs** [comment]
Hey, can you take a screenshot in the `stable-diffusion-webui` directory. Scroll down to the bottom, I wanna see what's inside.
And a screenshot from the Git tab. 

<details>
	<summary>Like these : (click to show)</summary>

![Snapshot_2024-10-03_232504](https://github.com/user-attachments/assets/31e29061-f7d7-46fa-8251-e506235cec1b)

![Snapshot_2024-10-03_232423](https://github.com/user-attachments/assets/16a49bbb-167f-4dbe-91ec-ea17de2a6abc)
</details>

**Comment by Mazhd** [comment]
Hey, thanks for the reply!

I fixed the issue...
I realized that it didnt clone the repo correctly as I made the project, so I remade it and made sure to enter the correct links. Thanks! :)

**Comment by ffxvs** [comment]
Yeah, I know it's most likely because git didn't clone the repo properly. But I don't know the cause.
I can't reproduce the issue and this is the second time someone reporting the same issue, so I'm curious.
