### ISSUE TITLE
Problem with installing models from civit.ai 

### ISSUE THREAD

**Issue by mertayd0** [ffxvs/sd-webui-complete-setup#20]
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.

I tried wget "civit.ai model download link" but got this error. I already put my API key btw

**Comment by mertayd0** [comment]
And is there a way to download private models directly from huggingface?

**Comment by ffxvs** [comment]
> HTTP request sent, awaiting response... 401 Unauthorized
> 
> Username/Password Authentication Failed.
> 
> I tried wget "civit.ai model download link" but got this error. I already put my API key btw

I already provide `Install from URLs` cell for people to download models manually, so why you download models using wget ?
API Key that you input doesn't work outside my ipynb notebooks.

<br>

> And is there a way to download private models directly from huggingface?

I haven't implemented it yet. Soon.
Thanks for reminding me.

**Comment by mertayd0** [comment]
Thanks man! It's sounds stupid but I am really not good at Jupyterlab thing. Should I put the link between brackets in the Install from URLs cell? I tried it but didn't worked that way.

**Comment by ffxvs** [comment]
Put your link between brackets and quotation marks. Add comma at the end if you want to put multiple links.

It should look like this :

```python
other_models = ['https://huggingface.co/Lykon/DreamShaper/resolve/main/DreamShaper_8_pruned.safetensors']
# or
other_models = [
    'https://huggingface.co/Lykon/DreamShaper/resolve/main/DreamShaper_8_pruned.safetensors',
    'https://civitai.com/api/download/models/201259?type=Model&format=SafeTensor&size=pruned&fp=fp16'
]
```

**Comment by ffxvs** [comment]
HuggingFace support has been added.

[Update 2024.10.15](https://github.com/ffxvs/sd-webui-complete-setup/discussions/22)
[WebUI Settings](https://github.com/ffxvs/sd-webui-complete-setup/wiki/WebUI-Guide#11-initialization)
