### ISSUE TITLE
With regard to the specification to update FORGE every time it is started.

### ISSUE THREAD

**Issue by gihepa988** [ffxvs/sd-webui-complete-setup#21]
Hello, I am a user of the paperspace version of FORGE.
I am very happy that it is currently very stable and usable. Thank you very much. I just have a couple of concerns.

In "1.1. Initialisation", is it possible to stop the automatic update of FORGE, which is started every time because "REQUIRED EVERY TIME YOU START THE MACHINE"? The UI is stable and running now, but there are a lot of updates, so I would like to stop updating when it is stable.

In addition, we want to prevent the 'config.json' from being automatically initialised with forge updates. It is a hassle to reconfigure it every time. I apologise if I have made a mistake in my configuration or usage.

These are the questions. I am Asian and my English is not good, I am translating this in deepl so some sentences may be wrong. My apologies.

**Comment by ffxvs** [comment]
Hello, thank you for using my work.

> In "1.1. Initialisation", is it possible to stop the automatic update of FORGE, which is started every time because "REQUIRED EVERY TIME YOU START THE MACHINE"? The UI is stable and running now, but there are a lot of updates, so I would like to stop updating when it is stable.

For this matter, I can add an option to enable or disable update.

<br>

> In addition, we want to prevent the 'config.json' from being automatically initialised with forge updates. It is a hassle to reconfigure it every time. I apologise if I have made a mistake in my configuration or usage.

What settings do you usually change ?
`config.json` will only be downloaded when it doesn't exist or when I force it to download the latest version because I changed some settings.

**Comment by gihepa988** [comment]
Thank you for your reply.

> > In "1.1. Initialisation", is it possible to stop the automatic update of FORGE, which is started every time because "REQUIRED EVERY TIME YOU START THE MACHINE"? The UI is stable and running now, but there are a lot of updates, so I would like to stop updating when it is stable.
> 
> For this matter, I can add an option to enable or disable update.

You have the option to turn off automatic updates - how can I do this? I can't find it in the guide.



>> In addition, we want to prevent the 'config.json' from being automatically initialised with forge updates. It is a hassle to reconfigure it every time. I apologise if I have made a mistake in my configuration or usage.
> 
> What settings do you usually change ?
> config.json will only be downloaded when it doesn't exist or when I force it to download the latest version because I changed some settings.

If I turn off automatic webui updates, does that mean that the config.json will not be updated accordingly?

**Comment by ffxvs** [comment]
> You have the option to turn off automatic updates - how can I do this? I can't find it in the guide.  

No, I mean can add the option later
<br>

> If I turn off automatic webui updates, does that mean that the config.json will not be updated accordingly?

I can also add that option later. You can also use your own config.json by replacing it in the `shared-storage` directory.

But, tell me first what settings do you usually change ?
I need to know that to avoid unwanted things.

**Comment by gihepa988** [comment]
> I can also add that option later. You can also use your own config.json by replacing it in the `shared-storage` directory.
>
Does this mean that it is inevitable that the system is currently updated every time it is started?


> But, tell me first what settings do you usually change ? I need to know that to avoid unwanted things.
>
For example, minor changes to language, file naming patterns, storage directories, etc., but the number of changes can be cumbersome. I now deal with this by saving my config.json and overwriting it every time it is initialised.

**Comment by ffxvs** [comment]
> Does this mean that it is inevitable that the system is currently updated every time it is started?

**Yes, for now.**
<br>

> For example, minor changes to language, file naming patterns, storage directories, etc., but the number of changes can be cumbersome. I now deal with this by saving my config.json and overwriting it every time it is initialised.

I will add an option for this in the future update, so users can use their own config.json.

Is there anything you still don't understand?
It looks like you are having a hard time understanding my answer.

**Comment by gihepa988** [comment]
Understood. I look forward to additional options. 
Thank you very much for taking the time to answer my questions.

**Comment by ffxvs** [comment]
- Auto update Forge option has been added.
- `config.json` will not be re-downloaded when running `1.1. Initialization` cell.
- Support for custom `config.json`  and `ui-config.json`.

[Update 2024.10.15](https://github.com/ffxvs/sd-webui-complete-setup/discussions/22)
[WebUI Settings](https://github.com/ffxvs/sd-webui-complete-setup/wiki/WebUI-Guide#11-initialization)
