### ISSUE TITLE
Pre Installed Content

### ISSUE THREAD

**Issue by xblitzarts** [ffxvs/sd-webui-complete-setup#4]
Hello! First of all, I'm glad that Forge is available for RunPod, I've been waiting for it :D

Now, I managed to install it and get it running, but in the preinstalled content tab (VAE, embeddings, upscalers, etc.), it doesn't install them; it leaves the directories empty. I was looking into how to solve this, but I couldn't find a way.

I hope there's a solution. In the meantime, I'll download the content manually. Thanks!

**Comment by ffxvs** [comment]
Does this happen in `sd15_resource_lists.ipynb` or `sdxl_resource_lists.ipynb` ?

**Comment by xblitzarts** [comment]
i try the sd1.5 for now

**Comment by ffxvs** [comment]
I've checked it and I didn't find any problems. Are you sure you have followed the instructions correctly ?
Any information would be useful.
