### ISSUE TITLE
Web UI

### ISSUE THREAD

**Issue by xenstar** [ffxvs/sd-webui-complete-setup#5]
Hi

Paperspace doesn't allow Ngrok. How you are exposing it to the public? 

And can you add support for foocus??

**Comment by ffxvs** [comment]
> How you are exposing it to the public?

Using Paperspace's internal port. Just run it and a link will appear 
`https://tensorboard-xxxxx.paperspacegradient.com`


> And can you add support for foocus??

I will consider it. Just not anytime soon.

**Comment by xenstar** [comment]
> Using Paperspace's internal port. Just run it and a link will appear
> `https://tensorboard-xxxxx.paperspacegradient.com`

I was trying to setup the facefusion in this way, can you give me the code that I can run which will give me a link like this "https://tensorboard-xxxxx.paperspacegradient.com" 

Or any document, where I can see the details.

**Comment by ffxvs** [comment]
Is Facefusion a standalone web app ?
And you want to run it like I did with the Web UI ?

**Comment by xenstar** [comment]
> Is Facefusion a standalone web app ? And you want to run it like I did with the Web UI ?

Yes correct - https://github.com/facefusion/facefusion


And you want to run it like I did with the Web UI ? - Yes.

**Comment by ffxvs** [comment]
Why not just use the extension version of Facefusion ?
https://github.com/diffus-me/sd-webui-facefusion
Just curious
