### ISSUE TITLE
Corrupted configs files make launching Web UI fail

### ISSUE THREAD

**Issue by Dreadboberts** [ffxvs/sd-webui-complete-setup#7]
Hi, Awesome setup. I've really been enjoying exploring all the options. Thanks for for putting all the work into it.  I'm running into similar issue as the previous person but as everything has been working great for me up till yesterday, I assume its a different issue. Very new to all this so its very likely an oversight on my end but I've exhausted the very short list of troubleshooting methods I have, I closed out of all my Notebooks and tried to start fresh, but that didn't help. That's it. Thats my trouble shooting skill level. Here are a couple screen shots of the error I'm seeing:
![Screenshot 2024-06-05 021758](https://github.com/ffxvs/sd-webui-complete-setup/assets/168033208/2e3a85d7-7cd6-43ac-b8ed-c65397b42f36)
![Screenshot 2024-06-05 021821](https://github.com/ffxvs/sd-webui-complete-setup/assets/168033208/658e6f2b-7431-4e16-8239-94017eadd3a0)

Thanks again

**Comment by ffxvs** [comment]
Hi!
Can you run the notebook again up to a 1.3 Shared Storage cell ?
Then attach config.json file inside `shared-storage/config` directory.
I was messing around with config.json recently so there might be something unexpected.

And is this Runpod or Paperspace ?

**Comment by Dreadboberts** [comment]
Hey,
Thanks, I'm using Paperspace.
Ok, attaching config.json file, but it looks empty (so does the ui-config file).
[config.json](https://github.com/user-attachments/files/15610055/config.json)

 I think you're right,  I figured I'd try replacing both config files the with their respective files on github and that got it to launch so thats cool!

**Comment by ffxvs** [comment]
Since ui-config.json is also empty and I didn't touch it at all, It looks like a connection issue where Paperspace fails to download the configs files and just creates empty files. 

Next time if you face this issue again you can delete those files and run `2.1. Web UI` cell. This will download the configs files again if they don't exist.

**Comment by Dreadboberts** [comment]
Ok, Right on. Thanks
