### ISSUE TITLE
Error: pathspec '29be1da' did not match any file(s) known to git

### ISSUE THREAD

**Issue by AtemSchiffer** [ffxvs/sd-webui-complete-setup#9]
Hi, I have deleted and installed papers multiple times and I have this error when running the installation cell

Installing Stable Diffusion Web UI Forge...
error: pathspec '29be1da' did not match any file(s) known to git

![WhatsApp Image 2024-07-30 at 19 58 38](https://github.com/user-attachments/assets/84adee50-0d03-4b1f-a5ef-c9af22136bd8)

**Comment by ffxvs** [comment]
Fixed in forge notebook version 2024.07.31. 
Sorry for the inconvenience. This is a mistake I made in the previous update.
